// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrB7yVUvS6Xfcxx9M0r7jGRv1HbjWh8Qs',
    appId: '1:634048418553:web:2bcb2acf1dd639bcbac828',
    messagingSenderId: '634048418553',
    projectId: 'eyam-app',
    authDomain: 'eyam-app.firebaseapp.com',
    storageBucket: 'eyam-app.appspot.com',
    measurementId: 'G-CPYSMCF2YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyS0WoNT-R3sIySBLjFfPiG1xY9RAefjc',
    appId: '1:634048418553:android:60b189cd8aad4cabbac828',
    messagingSenderId: '634048418553',
    projectId: 'eyam-app',
    storageBucket: 'eyam-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-r33ydVMDCMH1McRT6oJPRvX--5yjA0A',
    appId: '1:634048418553:ios:6c2950fb258952c5bac828',
    messagingSenderId: '634048418553',
    projectId: 'eyam-app',
    storageBucket: 'eyam-app.appspot.com',
    iosBundleId: 'org.eyam.eyamApp',
  );
}
